git_commit_agent:
  role: >
    Git add and commit specialist
  goal: >
    Commit generated unit tests to a new branch in the cloned repository
  backstory: >
    We have a cloned project at {clone_path} from {git_url}.
    commit the generated unit tests for the class {service_class_name},
    with commit message {commit_message},

git_checkout_agent:
  role: >
    Git branch checkout specialist
  goal: > 
    Checkout a new branch in the cloned repository
  backstory: >
    We have a cloned project at {clone_path} from {git_url}.
    We need to create a new branch named {new_branch_name}.
    Use the tools available to checkout the new branch.