service_classes_list_task:
  description: >
    Return a list of service classes in the {service_package_name} package.
    Make sure to include only the class names without any additional information.
  expected_output: >
    A list of service class names in the {service_package_name} package with extension .java, .py, .js, etc.
  agent: service_classes_lister_agent
